# Generated by Django 5.1.1 on 2024-11-09 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.IntegerField()),
                ('tipo_equipo', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('icono', models.ImageField(blank=True, null=True, upload_to='medallas/')),
                ('puntos_necesarios', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('puntos_otorgados', models.IntegerField()),
                ('requisito', models.IntegerField(help_text='Ejemplo: cantidad de servicios completados o puntos a alcanzar')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('manual', models.TextField(blank=True, null=True)),
                ('video', models.TextField(blank=True, null=True)),
                ('tipo_servicio', models.CharField(blank=True, max_length=100, null=True)),
                ('equipo_marca', models.CharField(blank=True, max_length=100, null=True)),
                ('equipo_modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('puntuacion', models.FloatField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceTrack.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('calificacion', models.IntegerField(blank=True, null=True)),
                ('comentario_cliente', models.TextField(blank=True, null=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceTrack.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Enlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enlace', models.TextField()),
                ('descripcion', models.TextField()),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceTrack.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('correo', models.EmailField(max_length=100)),
                ('celular', models.CharField(max_length=20)),
                ('puntos', models.IntegerField(default=0)),
                ('medallas', models.ManyToManyField(blank=True, related_name='usuarios', to='ServiceTrack.medalla')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceTrack.rol')),
            ],
        ),
        migrations.AddField(
            model_name='servicio',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnico_servicios', to='ServiceTrack.usuario'),
        ),
        migrations.CreateModel(
            name='RegistroPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_obtenidos', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceTrack.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ObservacionIncidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('tipo_observacion', models.CharField(max_length=100)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(max_length=50)),
                ('fecha_reportada', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceTrack.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceTrack.usuario'),
        ),
    ]
