# Generated by Django 5.1.1 on 2025-01-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceTrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
