# Generated by Django 5.1.1 on 2024-11-12 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceTrack', '0003_servicio_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('cumplido', models.BooleanField(default=False)),
                ('reto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceTrack.reto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reto',
            name='completado_por',
            field=models.ManyToManyField(related_name='retos_completados', through='ServiceTrack.RetoUsuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
